import React, { useCallback, useState } from 'react';
import { useMedicine } from '../context/MedicineContext';
import { useModalDismiss } from '../hooks/useModalDismiss';
import {
  X, 
  Printer, 
  Copy, 
  Check, 
  FileText, 
  ShieldCheck, 
  Flame, 
  Clock, 
  AlertTriangle,
  Pill
} from 'lucide-react';

export function DoctorReportModal() {
  const { 
    doctorReportOpen, 
    setDoctorReportOpen, 
    medicines, 
    results, 
    personalNotes 
  } = useMedicine();

  const [copied, setCopied] = useState(false);
  const [providerName, setProviderName] = useState(() => localStorage.getItem('medcheck_user_name') || '');

  // Stable identity: the dismiss hook focuses the dialog whenever its dependencies
  // change, and this modal contains a text input -- an inline arrow here would pull
  // focus back out of it on every keystroke.
  const closeModal = useCallback(() => setDoctorReportOpen(false), [setDoctorReportOpen]);
  const dialogRef = useModalDismiss(doctorReportOpen, closeModal);

  if (!doctorReportOpen) return null;

  const interactions = results?.interactions || [];
  const giScore = results?.composite_gi_score || 0;
  const foodConflicts = results?.food_conflicts || [];
  const currentDate = new Date().toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });

  const handleCopyMarkdown = () => {
    let reportMd = `# MEDCHECK CLINICAL SAFETY SUMMARY\n`;
    reportMd += `**Date:** ${currentDate}\n`;
    if (providerName) reportMd += `**Patient / Provider:** ${providerName}\n`;
    reportMd += `**Active Regimen (${medicines.length}):** ${medicines.map(m => m.name).join(', ')}\n\n`;

    reportMd += `## 1. COMPOSITE RISK METRICS\n`;
    reportMd += `- Stomach Guardian Score: ${giScore}/100 (${results?.composite_gi_tier || 'gentle'})\n`;
    reportMd += `- Identified Interactions: ${interactions.length}\n`;
    reportMd += `- Food & Timing Conflicts: ${foodConflicts.length}\n\n`;

    if (interactions.length > 0) {
      reportMd += `## 2. DRUG-DRUG INTERACTIONS\n`;
      interactions.forEach((i, idx) => {
        reportMd += `### [${i.severity.toUpperCase()}] ${i.drug_a} + ${i.drug_b}\n`;
        reportMd += `- **Explanation:** ${i.explanation}\n`;
        if (i.mechanism) reportMd += `- **Mechanism:** ${i.mechanism}\n`;
        if (i.action_guidance) reportMd += `- **Guidance:** ${i.action_guidance}\n\n`;
      });
    }

    if (foodConflicts.length > 0) {
      reportMd += `## 3. FOOD & LIFESTYLE RESTRICTIONS\n`;
      foodConflicts.forEach(f => {
        reportMd += `- **${f.medicine_a} + ${f.medicine_b}** (${f.conflict_type}): ${f.conflict} _Recommended:_ ${f.recommended_schedule}\n`;
      });
      reportMd += `\n`;
    }

    reportMd += `## 4. PATIENT REGIMEN NOTES\n`;
    medicines.forEach(m => {
      const note = personalNotes[m.name.toLowerCase()];
      if (note) {
        reportMd += `- **${m.name}**: ${note}\n`;
      }
    });

    reportMd += `\n---\n*Disclaimer: Generated by MEDCHECK for clinical reference. Consult licensed medical providers for prescribing changes.*`;

    navigator.clipboard.writeText(reportMd);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/40 modal-backdrop overflow-y-auto"
      // Clicking the backdrop closes; the guard keeps clicks that bubble up from
      // inside the panel from dismissing it.
      onClick={(e) => {
        if (e.target === e.currentTarget) closeModal();
      }}
    >
      {/* role/aria-modal mark the page behind as inert for assistive tech, and
          aria-labelledby names the dialog -- without it the announcement is just
          "dialog". tabIndex={-1} lets the dismiss hook move focus in on open
          without adding a tab stop. */}
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="doctor-report-title"
        aria-describedby="doctor-report-subtitle"
        tabIndex={-1}
        className="card max-w-3xl w-full max-h-[90vh] flex flex-col p-0 overflow-hidden shadow-2xl sheet-enter outline-none"
      >
        {/* Modal Top Bar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--border-default)] bg-[var(--bg-surface)]">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-[4px] bg-[var(--accent)] text-[var(--text-inverse)] flex items-center justify-center">
              <FileText className="w-4 h-4" aria-hidden="true" />
            </div>
            <div>
              <h2
                id="doctor-report-title"
                className="font-serif text-[22px] font-bold text-[var(--text-primary)] leading-tight"
              >
                Doctor's Safety Summary Report
              </h2>
              <p id="doctor-report-subtitle" className="text-xs text-[var(--text-muted)] font-sans">
                Generated {currentDate} • Clinical Brief for Office Visits
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopyMarkdown}
              className="btn-secondary text-xs py-1.5 px-3 min-h-[36px] flex items-center gap-1.5"
              aria-label="Copy the full report to the clipboard as text"
            >
              {copied ? (
                <Check className="w-3.5 h-3.5 text-[var(--severity-low)]" aria-hidden="true" />
              ) : (
                <Copy className="w-3.5 h-3.5 text-[var(--text-primary)]" aria-hidden="true" />
              )}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>

            <button
              type="button"
              onClick={handlePrint}
              className="btn-primary text-xs py-1.5 px-3 min-h-[36px] flex items-center gap-1.5"
              aria-label="Print this clinical brief"
            >
              <Printer className="w-3.5 h-3.5" aria-hidden="true" />
              <span>Print Brief</span>
            </button>

            <button
              type="button"
              onClick={closeModal}
              aria-label="Close doctor's safety summary report"
              className="p-1.5 rounded-[4px] text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[#E2E8F0] transition-colors ml-1 cursor-pointer"
            >
              <X className="w-4 h-4" aria-hidden="true" />
            </button>
          </div>
        </div>

        {/* Modal Body: Printable Clinical Summary Sheet */}
        <div className="flex-1 overflow-y-auto p-6 space-y-5 bg-[var(--bg-surface)] text-[var(--text-primary)]">
          {/* Header Info */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-3.5 bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[8px]">
            <div>
              {/* Was a bare <span>, so the only accessible name this field had was
                  its placeholder -- which disappears the moment anything is typed.
                  A real <label htmlFor> also makes the caption a click target. */}
              <label
                htmlFor="report-patient-name"
                className="text-xs text-[var(--text-muted)] uppercase block font-bold"
              >
                Patient / Session
              </label>
              <input
                id="report-patient-name"
                name="patientName"
                type="text"
                autoComplete="name"
                value={providerName}
                onChange={(e) => setProviderName(e.target.value)}
                placeholder="Enter patient name..."
                className="bg-transparent text-sm font-semibold text-[var(--text-primary)] outline-none border-b border-transparent focus:border-[var(--border-hover)] w-full font-serif"
              />
            </div>
            <div>
              <span className="text-xs text-[var(--text-muted)] uppercase block font-bold">Active Regimen</span>
              <span className="text-sm font-semibold text-[var(--text-primary)] font-serif">
                {medicines.map(m => m.name).join(', ') || 'No medications'}
              </span>
            </div>
            <div>
              <span className="text-xs text-[var(--text-muted)] uppercase block font-bold">Stomach Health Score</span>
              <div className="flex items-center gap-1.5 mt-0.5">
                <span className="metric text-base text-[var(--severity-moderate)]">{giScore}/100</span>
                <span className="tag">
                  {results?.composite_gi_tier?.toUpperCase() || 'GENTLE'}
                </span>
              </div>
            </div>
          </div>

          {/* Section 1: Identified Drug Interactions */}
          <div className="space-y-2.5">
            <h3 className="font-serif text-[18px] font-bold text-[var(--text-primary)] border-b border-[var(--border-default)] pb-1.5 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-[var(--text-primary)]" aria-hidden="true" />
              <span>1. Drug Interaction Matrix ({interactions.length})</span>
            </h3>

            {interactions.length === 0 ? (
              <p className="text-xs text-[var(--text-muted)] italic p-2 bg-[var(--bg-elevated)] rounded">
                No acute pharmacokinetic or pharmacodynamic drug interactions identified across loaded medicines.
              </p>
            ) : (
              <div className="space-y-2">
                {interactions.map((i, idx) => (
                  <div
                    key={`${i.drug_a}-${i.drug_b}-${idx}`}
                    className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[6px] text-xs space-y-1"
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-serif font-bold text-[15px] text-[var(--text-primary)]">
                        {i.drug_a} + {i.drug_b}
                      </span>
                      <span className={`tag ${
                        i.severity === 'high'
                          ? 'tag-danger'
                          : i.severity === 'moderate'
                          ? 'tag-warning'
                          : 'tag-success'
                      }`}>
                        {i.severity?.toUpperCase()} RISK
                      </span>
                    </div>
                    <p className="text-xs text-[var(--text-secondary)]">{i.explanation}</p>
                    {i.mechanism && (
                      <p className="text-xs text-[var(--text-muted)] font-mono">
                        Mechanism: {i.mechanism}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Section 2: Food & Administration Guidance */}
          <div className="space-y-2.5">
            <h3 className="font-serif text-[18px] font-bold text-[var(--text-primary)] border-b border-[var(--border-default)] pb-1.5 flex items-center gap-2">
              <Clock className="w-4 h-4 text-[var(--text-primary)]" aria-hidden="true" />
              <span>2. Food, Beverage & Timing Rules ({foodConflicts.length})</span>
            </h3>

            {foodConflicts.length === 0 ? (
              <p className="text-xs text-[var(--text-muted)] italic p-2 bg-[var(--bg-elevated)] rounded">
                Standard water co-administration recommended. No acute food timing blocks.
              </p>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {foodConflicts.map((f, idx) => (
                  <div
                    key={`${f.medicine_a}-${f.medicine_b}-${f.conflict_type}-${idx}`}
                    className="p-2.5 bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[6px] text-xs"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <span className="font-serif font-bold text-[14px] text-[var(--text-primary)]">
                        {f.medicine_a} + {f.medicine_b}
                      </span>
                      <span className="tag tag-warning whitespace-nowrap">{f.conflict_type}</span>
                    </div>
                    <p className="text-xs font-semibold text-[var(--text-primary)] mt-1">{f.conflict}</p>
                    <p className="text-xs text-[var(--text-muted)] mt-0.5">
                      Recommended: {f.recommended_schedule}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Section 3: Patient Specific Notes */}
          <div className="space-y-2.5">
            <h3 className="font-serif text-[18px] font-bold text-[var(--text-primary)] border-b border-[var(--border-default)] pb-1.5 flex items-center gap-2">
              <Pill className="w-4 h-4 text-[var(--text-primary)]" aria-hidden="true" />
              <span>3. Patient Notes & Administration Context</span>
            </h3>

            <div className="space-y-1.5">
              {medicines.map((m) => {
                const note = personalNotes[m.name.toLowerCase()];
                return (
                  <div key={m.id} className="p-2.5 bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[6px] text-xs flex items-start gap-2">
                    <span className="font-serif font-bold text-[14px] text-[var(--text-primary)] min-w-[100px]">{m.name}:</span>
                    <span className="text-xs text-[var(--text-secondary)] italic">
                      {note || 'No custom notes logged.'}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="pt-3 border-t border-[var(--border-default)] text-center text-xs text-[var(--text-muted)]">
            MEDCHECK Clinical Brief • OpenFDA Prescribing Data Validated • Informational Summary
          </div>
        </div>
      </div>
    </div>
  );
}
