import React, { useState } from 'react';
import { useMedicine } from '../context/MedicineContext';
import { 
  X, 
  Printer, 
  Copy, 
  Check, 
  FileText, 
  ShieldCheck, 
  Flame, 
  Clock, 
  AlertTriangle,
  Pill
} from 'lucide-react';

export function DoctorReportModal() {
  const { 
    doctorReportOpen, 
    setDoctorReportOpen, 
    medicines, 
    results, 
    personalNotes 
  } = useMedicine();

  const [copied, setCopied] = useState(false);
  const [providerName, setProviderName] = useState(() => localStorage.getItem('medcheck_user_name') || '');

  if (!doctorReportOpen) return null;

  const interactions = results?.interactions || [];
  const giScore = results?.composite_gi_score || 0;
  const foodConflicts = results?.food_conflicts || [];
  const currentDate = new Date().toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });

  const handleCopyMarkdown = () => {
    let reportMd = `# MEDCHECK CLINICAL SAFETY SUMMARY\n`;
    reportMd += `**Date:** ${currentDate}\n`;
    if (providerName) reportMd += `**Patient / Provider:** ${providerName}\n`;
    reportMd += `**Active Regimen (${medicines.length}):** ${medicines.map(m => m.name).join(', ')}\n\n`;

    reportMd += `## 1. COMPOSITE RISK METRICS\n`;
    reportMd += `- Stomach Guardian Score: ${giScore}/100 (${results?.composite_gi_tier || 'gentle'})\n`;
    reportMd += `- Identified Interactions: ${interactions.length}\n`;
    reportMd += `- Food & Timing Conflicts: ${foodConflicts.length}\n\n`;

    if (interactions.length > 0) {
      reportMd += `## 2. DRUG-DRUG INTERACTIONS\n`;
      interactions.forEach((i, idx) => {
        reportMd += `### [${i.severity.toUpperCase()}] ${i.drug_a} + ${i.drug_b}\n`;
        reportMd += `- **Explanation:** ${i.explanation}\n`;
        if (i.mechanism) reportMd += `- **Mechanism:** ${i.mechanism}\n`;
        if (i.action_guidance) reportMd += `- **Guidance:** ${i.action_guidance}\n\n`;
      });
    }

    if (foodConflicts.length > 0) {
      reportMd += `## 3. FOOD & LIFESTYLE RESTRICTIONS\n`;
      foodConflicts.forEach(f => {
        reportMd += `- **${f.drug}**: ${f.title} — ${f.description}\n`;
      });
      reportMd += `\n`;
    }

    reportMd += `## 4. PATIENT REGIMEN NOTES\n`;
    medicines.forEach(m => {
      const note = personalNotes[m.name.toLowerCase()];
      if (note) {
        reportMd += `- **${m.name}**: ${note}\n`;
      }
    });

    reportMd += `\n---\n*Disclaimer: Generated by MEDCHECK for clinical reference. Consult licensed medical providers for prescribing changes.*`;

    navigator.clipboard.writeText(reportMd);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/40 modal-backdrop overflow-y-auto">
      <div className="card max-w-3xl w-full max-h-[90vh] flex flex-col p-0 overflow-hidden shadow-2xl sheet-enter">
        {/* Modal Top Bar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--border-default)] bg-[var(--bg-surface)]">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-[4px] bg-[var(--accent)] text-[var(--text-inverse)] flex items-center justify-center">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h2 className="font-serif text-[22px] font-bold text-[var(--text-primary)] leading-tight">
                Doctor's Safety Summary Report
              </h2>
              <p className="text-xs text-[var(--text-muted)] font-sans">
                Generated {currentDate} • Clinical Brief for Office Visits
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="btn-secondary text-xs py-1.5 px-3 min-h-[36px] flex items-center gap-1.5"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-[var(--severity-low)]" /> : <Copy className="w-3.5 h-3.5 text-[var(--text-primary)]" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="btn-primary text-xs py-1.5 px-3 min-h-[36px] flex items-center gap-1.5"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Brief</span>
            </button>

            <button
              onClick={() => setDoctorReportOpen(false)}
              className="p-1.5 rounded-[4px] text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[#E2E8F0] transition-colors ml-1 cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Modal Body: Printable Clinical Summary Sheet */}
        <div className="flex-1 overflow-y-auto p-6 space-y-5 bg-[var(--bg-surface)] text-[var(--text-primary)]">
          {/* Header Info */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-3.5 bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[8px]">
            <div>
              <span className="text-xs text-[var(--text-muted)] uppercase block font-bold">Patient / Session</span>
              <input
                type="text"
                value={providerName}
                onChange={(e) => setProviderName(e.target.value)}
                placeholder="Enter patient name..."
                className="bg-transparent text-sm font-semibold text-[var(--text-primary)] outline-none border-b border-transparent focus:border-[var(--border-hover)] w-full font-serif"
              />
            </div>
            <div>
              <span className="text-xs text-[var(--text-muted)] uppercase block font-bold">Active Regimen</span>
              <span className="text-sm font-semibold text-[var(--text-primary)] font-serif">
                {medicines.map(m => m.name).join(', ') || 'No medications'}
              </span>
            </div>
            <div>
              <span className="text-xs text-[var(--text-muted)] uppercase block font-bold">Stomach Health Score</span>
              <div className="flex items-center gap-1.5 mt-0.5">
                <span className="metric text-base text-[var(--severity-moderate)]">{giScore}/100</span>
                <span className="tag">
                  {results?.composite_gi_tier?.toUpperCase() || 'GENTLE'}
                </span>
              </div>
            </div>
          </div>

          {/* Section 1: Identified Drug Interactions */}
          <div className="space-y-2.5">
            <h3 className="font-serif text-[18px] font-bold text-[var(--text-primary)] border-b border-[var(--border-default)] pb-1.5 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-[var(--text-primary)]" />
              <span>1. Drug Interaction Matrix ({interactions.length})</span>
            </h3>

            {interactions.length === 0 ? (
              <p className="text-xs text-[var(--text-muted)] italic p-2 bg-[var(--bg-elevated)] rounded">
                No acute pharmacokinetic or pharmacodynamic drug interactions identified across loaded medicines.
              </p>
            ) : (
              <div className="space-y-2">
                {interactions.map((i, idx) => (
                  <div key={idx} className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[6px] text-xs space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="font-serif font-bold text-[15px] text-[var(--text-primary)]">
                        {i.drug_a} + {i.drug_b}
                      </span>
                      <span className={`tag ${
                        i.severity === 'high'
                          ? 'tag-danger'
                          : i.severity === 'moderate'
                          ? 'tag-warning'
                          : 'tag-success'
                      }`}>
                        {i.severity?.toUpperCase()} RISK
                      </span>
                    </div>
                    <p className="text-xs text-[var(--text-secondary)]">{i.explanation}</p>
                    {i.mechanism && (
                      <p className="text-xs text-[var(--text-muted)] font-mono">
                        Mechanism: {i.mechanism}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Section 2: Food & Administration Guidance */}
          <div className="space-y-2.5">
            <h3 className="font-serif text-[18px] font-bold text-[var(--text-primary)] border-b border-[var(--border-default)] pb-1.5 flex items-center gap-2">
              <Clock className="w-4 h-4 text-[var(--text-primary)]" />
              <span>2. Food, Beverage & Timing Rules ({foodConflicts.length})</span>
            </h3>

            {foodConflicts.length === 0 ? (
              <p className="text-xs text-[var(--text-muted)] italic p-2 bg-[var(--bg-elevated)] rounded">
                Standard water co-administration recommended. No acute food timing blocks.
              </p>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {foodConflicts.map((f, idx) => (
                  <div key={idx} className="p-2.5 bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[6px] text-xs">
                    <div className="flex items-center justify-between">
                      <span className="font-serif font-bold text-[14px] text-[var(--text-primary)]">{f.drug}</span>
                      <span className="tag tag-warning">{f.severity}</span>
                    </div>
                    <p className="text-xs font-semibold text-[var(--text-primary)] mt-1">{f.title}</p>
                    <p className="text-xs text-[var(--text-muted)] mt-0.5">{f.description}</p>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Section 3: Patient Specific Notes */}
          <div className="space-y-2.5">
            <h3 className="font-serif text-[18px] font-bold text-[var(--text-primary)] border-b border-[var(--border-default)] pb-1.5 flex items-center gap-2">
              <Pill className="w-4 h-4 text-[var(--text-primary)]" />
              <span>3. Patient Notes & Administration Context</span>
            </h3>

            <div className="space-y-1.5">
              {medicines.map((m) => {
                const note = personalNotes[m.name.toLowerCase()];
                return (
                  <div key={m.id} className="p-2.5 bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-[6px] text-xs flex items-start gap-2">
                    <span className="font-serif font-bold text-[14px] text-[var(--text-primary)] min-w-[100px]">{m.name}:</span>
                    <span className="text-xs text-[var(--text-secondary)] italic">
                      {note || 'No custom notes logged.'}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="pt-3 border-t border-[var(--border-default)] text-center text-xs text-[var(--text-muted)]">
            MEDCHECK Clinical Brief • OpenFDA Prescribing Data Validated • Informational Summary
          </div>
        </div>
      </div>
    </div>
  );
}
